### ISSUE TITLE
Is the DC FeatureCollection valid?

### ISSUE THREAD

**Issue by mapsam** [mapbox/mapnik-test-data#6]
This is mostly a question, but I've noticed the [DC_polygon.geo.json](https://github.com/mapbox/mapnik-test-data/blob/master/data/geojson/DC_polygon.geo.json) is valid in some cases, but invalid in others due to the LinearRing not having the same start and end point in the array.

```
[-77.0353,38.9939],
[-77.0024,38.9665],
[-76.9093,38.8953],
[-77.0407,38.7912],
[-77.0462,38.8405],
[-77.0407,38.8734],
[-77.1174,38.9336]
```

#### Where is it valid?

* **github** renders the geometry properly in their data view
* `geojson-validation` module returns `Valid!`

#### Where is it invalid?

* **geojson.io** shows an error and does not display the file
* **geojsonlint.com** says `the first and last positions in a LinearRing of coordinates must be the same`

Just looking for some clarification, and wondering if we should potentially update this in our fixtures to ensure we are testing valid/invalid geometries.

I can see @sgillies being helpful here :smile: 

cc/ @GretaCB @jakepruitt @springmeyer @flippmoke

**Comment by tmcw** [comment]
geojsonhint says no because

> A LinearRing is closed LineString with 4 or more positions. The first and last positions are equivalent (they represent equivalent points). 

fwiw, when in doubt, trust geojsonhint. It has, as far as I know, no bugs.

**Comment by springmeyer** [comment]
:+1:  on updating to be valid.@mapsam after fixing you'll likely need to re-publish which is done with https://github.com/mapbox/npm-internal.

**Comment by mapsam** [comment]
Great, thanks for the insight @tmcw! Looks like this feature is the cause of a failing test in `tilelive-omnivore` when running updated `node-mapnik` binaries for the `2.0` specification. I'll update this now so we can get those passing.
